### PR TITLE
feat: add image compression

### PR DESCRIPTION
**Pull request by steveoh**
this should compress these images to make them better for web viewing

### CODE REVIEW

**Comment by rkelson** [comment]
I ran into some other issues with the images I uploaded (wanting them all to be locase .jpg) so I need to fix some things and repair my local repo while rapping my head around the larger picture using desktop and eventually command line. I have a few other things going on right now and my plan is to try and devote time in the late afternoons to this.

So squash and merge is what you suggest at the moment?

**Comment by steveoh** [comment]
i prefer rebase and merge

**Comment by steveoh** [comment]
here's a bit of python to rename the files

```py
import os
from glob import glob


def rename(item):
    index, name = item
    os.rename(name, f'{name.lower()}.jpg'

files = glob('*.jpg')

[rename(photo) for photo in enumerate(files)]
```

**Comment by rkelson** [comment]
I need to do a couple other things before working on this. The problem way I do not know how to fix the extension once they were uploaded to github. I suppose the optimizer will fix that issue?
And the python would be run on my local repo or images? I was planning to just use dos to rename *.JPG *.jpg. Maybe later this afternoon we can have a hang out and discuss the bigger picture.

**Comment by steveoh** [comment]
The github action, which you might be calling the optimizer (correct me if I am wrong) will only compress images to reduce the file size; Nothing more.

If you want to change the files that are in github you will make the changes in your local copy of the repo and then push them to github.

Any changes that are made in github that your local copy doesn't know about need to be pulled down. After accepting this PR, in your local repo, you will need to call `git pull --rebase` to get the optimized images.

Then you can run the python (or DOS) to rename the files. Commit the new file names and push to github to complete your task. That way you will be renaming the optimized images.

I am happy to have a hangout later today if you need some guidance.

**Pull request merged**
